USE budget_tracker;

CREATE TABLE IF NOT EXISTS users (
    id CHAR(36) PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    fullname VARCHAR(255) NOT NULL,
    nickname VARCHAR(100),
    hashed_password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    email_verified BOOLEAN DEFAULT FALSE,
    joined_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE
    users
ADD
    COLUMN IF NOT EXISTS username VARCHAR(100) UNIQUE NOT NULL;

ALTER TABLE
    users
ADD
    COLUMN IF NOT EXISTS fullname VARCHAR(255) NOT NULL;

ALTER TABLE
    users
ADD
    COLUMN IF NOT EXISTS nickname VARCHAR(100);

ALTER TABLE
    users
ADD
    COLUMN IF NOT EXISTS hashed_password VARCHAR(255) NOT NULL;

ALTER TABLE
    users
ADD
    COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE NOT NULL;

ALTER TABLE
    users
ADD
    COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;

ALTER TABLE
    users
ADD
    COLUMN IF NOT EXISTS joined_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;