USE budget_tracker;

CREATE TABLE IF NOT EXISTS expense_categories (
    id CHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    amount DECIMAL(20, 2) NOT NULL DEFAULT 0.00,
    max_amount DECIMAL(20, 2),
    period_day INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    note VARCHAR(1000),
    created_by CHAR(36) NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);